#!/usr/bin/env python3
"""Convert PNG images to LVGL C array format for embedding in firmware."""

import sys
import os
import struct
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Install Pillow: pip install Pillow")
    sys.exit(1)


def png_to_lvgl_c(input_path: str, output_path: str, var_name: str = None):
    img = Image.open(input_path).convert("RGB")
    w, h = img.size

    if var_name is None:
        var_name = Path(input_path).stem.replace("-", "_").replace(" ", "_")

    pixels = []
    for y in range(h):
        for x in range(w):
            r, g, b = img.getpixel((x, y))
            # RGB565
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            pixels.append(rgb565)

    lines = [
        f"/* Auto-generated by tools/convert_image.py — do not edit */",
        f"#include \"lvgl.h\"",
        f"",
        f"static const uint8_t {var_name}_map[] = {{",
    ]

    row = []
    for px in pixels:
        row.append(f"0x{px & 0xFF:02X}, 0x{(px >> 8) & 0xFF:02X}")
        if len(row) == 8:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")

    lines += [
        f"}};",
        f"",
        f"const lv_img_dsc_t {var_name} = {{",
        f"    .header = {{",
        f"        .cf     = LV_COLOR_FORMAT_RGB565,",
        f"        .w      = {w},",
        f"        .h      = {h},",
        f"    }},",
        f"    .data_size = sizeof({var_name}_map),",
        f"    .data      = {var_name}_map,",
        f"}};",
    ]

    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Converted {input_path} ({w}x{h}) → {output_path}")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} input.png output.c [var_name]")
        sys.exit(1)
    var = sys.argv[3] if len(sys.argv) > 3 else None
    png_to_lvgl_c(sys.argv[1], sys.argv[2], var)
