#!/usr/bin/env python3
"""Generate version.h from git describe or VERSION file."""

import subprocess
import sys
import os


def get_version():
    try:
        v = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        return v
    except Exception:
        return "0.0.0-unknown"


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "main/version.h"
    version = get_version()
    content = f"""/* Auto-generated by tools/gen_version.py — do not edit */
#pragma once
#define APP_GIT_VERSION "{version}"
"""
    with open(out, "w") as f:
        f.write(content)
    print(f"version.h written: {version}")


if __name__ == "__main__":
    main()
